# Generated by Django 3.2.6 on 2021-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='weakness',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
